Update sfos-upgrade

diff --git a/usr/bin/sfos-upgrade b/usr/bin/sfos-upgrade
--- a/usr/bin/sfos-upgrade
+++ b/usr/bin/sfos-upgrade
@@ -52,7 +52,7 @@ askyes ()
 compare_versions ()
 {
   # Returns 0 if A = B, 1 if A < B, 2 if A > B.
-  # The result is solely provided in the return code, all error messages go directly to STDERR followed by exiting
+  # The result is solely provided in the return code, all error messages go directly to STDERR followed by exiting.
   if [ "$#" -ne "2" ]
   then
     echo "Aborting: Two parameters expected, but $# received!" 1>&2
@@ -85,6 +85,8 @@ compare_versions ()
   done
   return "$ret"
 }
+
+# Main script
 
 called="$(basename "$0")"
 if ! echo " $(id -un) $(id -Gn) " | fgrep -q ' root '
@@ -160,20 +162,33 @@ then
 fi
 for stop_release in $(echo -e "${recent_stop_releases}\n$known_stop_releases" | grep -v '^$' | sort -u)
 do
-  if [ "$( ( compare_versions "$installed_release" "$stop_release" ); echo "$?")" = "1" ] && [ "$( ( compare_versions "$upgrade_release" "$stop_release" ); echo "$?")" = "2" ] && true
-  then
-    echo "Notice: Upgrading from $installed_release to $upgrade_release would omit installing $stop_release as a stop release!" 1>&2
-    if [ -n "$set_ssu" ]
-    then echo "Thus upgrading to $stop_release instead." 1>&2
-    else
-     echo -n "Set SSU to $stop_release before upgrading (a negative reply aborts)?" 1>&2
-     askyes 1>&2
-     set_ssu="yes"
+  ( compare_versions "$stop_release" "$installed_release" )
+  case "$?" in
+  1|0)
+    ( compare_versions "$stop_release" "$upgrade_release" )
+    if [ "$?" = "2" ]
+    then
+      echo "Aborting: "
     fi
-    upgrade_release="$stop_release"
-    echo 1>&2
-    break
-  fi
+    ;;
+  2)
+    ( compare_versions "$stop_release" "$upgrade_release" )
+    if [ "$?" = "1" ]
+    then
+      echo "Notice: Upgrading from $installed_release to $upgrade_release would omit installing $stop_release as a stop release!" 1>&2
+      if [ -n "$set_ssu" ]
+      then echo "Thus upgrading to $stop_release instead." 1>&2
+      else
+       echo -n "Set SSU to $stop_release before upgrading (a negative reply aborts)?" 1>&2
+       askyes 1>&2
+       set_ssu="yes"
+      fi
+      upgrade_release="$stop_release"
+      echo 1>&2
+      break
+    fi
+    ;;
+  esac
 done
 
 if mount -t btrfs | cut -s -f 3 -d ' ' | grep -q '^/$'
