Fix checks for downgrading over stop releases (#30)
* Update sfos-upgrade

* Update sfos-upgrade

* Update sfos-upgrade

* Update sfos-upgrade

diff --git a/usr/bin/sfos-upgrade b/usr/bin/sfos-upgrade
--- a/usr/bin/sfos-upgrade
+++ b/usr/bin/sfos-upgrade
@@ -167,87 +167,151 @@ then
   echo >&2
 fi
 
-known_stop_releases="3.0.0.8\n2.2.0.29\n2.0.5.6\n2.0.0.10\n1.1.9.30\n1.1.7.28\n1.1.2.16\n1.0.2.5\n1.0.0.5"
-# 0.99.5.11, 1.0.0.5 and 1.0.1.10 are not documented to be "stop releases",
-# taking the information of sections 4 and 5 (in combination!) at
-# https://jolla.zendesk.com/hc/en-us/articles/201836347#4 into account.
-# But 2.0.5.6 seems to be a "stop release", at least on some devices, see comments thread to
-# https://together.jolla.com/question/207172/downgrade-sailfish-os/?answer=207190#post-id-207190
-# Also added 1.0.0.5 as a precaution, because it seems to be the oldest widely deployed SailfishOS
-# release (i.e., *on* and hence also *in* the "factory images" of the first commercially distributed
-# Jolla 1 phones), thus being the oldest one widely tested to upgrade from (and Jolla may assume
-# only early developers to have ever obtained an earlier release on their Jolla 1 phones, hence
-# not mentioning 1.0.0.5 in Jolla's "official" guides as a stop release).
-if ! recent_stop_releases="$(curl -sS https://jolla.zendesk.com/hc/en-us/articles/201836347 | sed -n '/id="4"/,/id="5"/p' | sed -n '/<ul>/,/<\/ul>/p' | sed -n '/<li>/,/<\/li>/p' | sed 's/<[^>]*>/\n/g' | tr -c '.0-9' '\n' | egrep '^[1-9]\.[0-9]\.[0-9]\.[0-9]$|^[1-9]\.[0-9]\.[0-9]\.[1-9][0-9]$')"
+if [ "$installed_release" != "$upgrade_release" ]
 then
-  echo "Warning: Failed to extract the current \"stop releases\" from https://jolla.zendesk.com/hc/en-us/articles/201836347#4" >&2
-  echo "Hence using an internal, potentially outdated list of stop releases instead." >&2
-  echo >&2
-fi
-for stop_release in $(echo -e "${recent_stop_releases}\n$known_stop_releases" | grep -v '^$' | sort -u)
-do
-  ( compare_versions "$stop_release" "$installed_release" ) > /dev/null
+  known_stop_releases="3.0.0.8\n2.2.0.29\n2.0.5.6\n2.0.0.10\n1.1.9.30\n1.1.7.28\n1.1.2.16\n1.0.2.5\n1.0.0.5"
+  # 0.99.5.11, 1.0.0.5 and 1.0.1.10 are not documented to be "stop releases",
+  # taking the information of sections 4 and 5 (in combination!) at
+  # https://jolla.zendesk.com/hc/en-us/articles/201836347#4 into account.
+  # But 2.0.5.6 seems to be a "stop release", at least on some devices, see comments thread to
+  # https://together.jolla.com/question/207172/downgrade-sailfish-os/?answer=207190#post-id-207190
+  # Also added 1.0.0.5 as a precaution, because it seems to be the oldest widely deployed SailfishOS
+  # release (i.e., *on* and hence also *in* the "factory images" of the first commercially distributed
+  # Jolla 1 phones), thus being the oldest one widely tested to upgrade from (and Jolla may assume
+  # only early developers to have ever obtained an earlier release on their Jolla 1 phones, hence
+  # not mentioning 1.0.0.5 in Jolla's "official" guides as a stop release).
+  if ! recent_stop_releases="$(curl -sS https://jolla.zendesk.com/hc/en-us/articles/201836347 | sed -n '/id="4"/,/id="5"/p' | sed -n '/<ul>/,/<\/ul>/p' | sed -n '/<li>/,/<\/li>/p' | sed 's/<[^>]*>/\n/g' | tr -c '.0-9' '\n' | egrep '^[1-9]\.[0-9]\.[0-9]\.[0-9]$|^[1-9]\.[0-9]\.[0-9]\.[1-9][0-9]$')"
+  then
+    echo "Warning: Failed to extract the current \"stop releases\" from https://jolla.zendesk.com/hc/en-us/articles/201836347#4" >&2
+    echo "Hence using an internal, potentially outdated list of stop releases instead." >&2
+    echo >&2
+  fi
+  all_stop_releases="$(echo -e "${recent_stop_releases}\n$known_stop_releases" | grep -v '^$' | sort -u)"
+  ( compare_versions "$installed_release" "$upgrade_release" ) > /dev/null
   ret="$?"
   case "$ret" in
-  [01])
-    # A general downgrade check is performed later; this solely deals with downgrading "below" stop releases.
-    field="$(( compare_versions "$stop_release" "$upgrade_release" ); ret="$?")"
-    case "${ret}-$field" in
-    [01]-?)
-      true
-      ;;
-    2-4)
-      echo "Warning: About to DOWNGRADE SailfishOS from $installed_release to ${upgrade_release}, which downgrades \"below\" the stop release $stop_release." >&2
-      echo "While downgrading between \"point releases\" seems to be generally feasible, doing so \"below\" a stop release bears the little extra danger of the changes making it a stop release not all being introduced with SailfishOS $(echo "$stop_release" | cut -f -3 -d '.').0 (e.g. with $stop_release and thus potentially downgrading \"across\" these changes, which would break this SailfishOS installation)." >&2
-      echo "The only absolutely safe way to achieve this is to execute a \"factory reset\", followed by UPgrading to the intended version.  Although one may try downgrading and if it fails or breaks some functionality, perform a \"factory reset\" (in the worst case at the recovery console)." >&2
-      echo >&2
-      break
-      ;;
-    2-?)
-      echo "Aborting: Trying to DOWNGRADE SailfishOS from $installed_release to ${upgrade_release}, which is \"across\" the stop release ${stop_release}!" >&2
-      echo "Doing that would likely break this SailfishOS installation." >&2
-      echo "The only way to achieve this properly is to execute a \"factory reset\", followed by UPgrading to the intended version." >&2
-      exit 3
-      ;;
-    *)
-      echo "Comparing versions in \"stop releases\" check failed." >&2
-      exit "$ret"
-      ;;
-    esac
+  0)  # Equality
+    echo "Noticed a harmless internal logical mistake: Equality was tested before!" >&2
+    echo >&2
     ;;
-  2)
-    ( compare_versions "$stop_release" "$upgrade_release" ) > /dev/null
-    ret="$?"
-    case "$ret" in
-    1)
-      echo "Notice: Upgrading from $installed_release to $upgrade_release would omit installing $stop_release as a stop release!" >&2
-      if [ -n "$set_ssu" ]
-      then echo "Thus upgrading to $stop_release instead." >&2
-      else
-       echo -n "Set SSU to $stop_release before upgrading (a negative reply aborts)?" >&2
-       askyes >&2
-       set_ssu="yes"
-      fi
-      upgrade_release="$stop_release"
-      echo >&2
-      break
-      ;;
-    [02])
-      # A general downgrade check is performed later; this solely deals with downgrading "below" stop releases (here: "or not").
-      break
-      ;;
-    *)
-      echo "Comparing versions in \"stop releases\" check failed." >&2
-      exit "$ret"
-      ;;
-    esac
+  1)  # Upgrade
+    # Iterating upwards through all stop releases:
+    for stop_release in $all_stop_releases
+    do
+      ( compare_versions "$stop_release" "$installed_release" ) > /dev/null
+      ret="$?"
+      case "$ret" in
+      [01])
+        true
+        ;;
+      2)  # Hit the first stop release, which is greater than the installed release.
+        ( compare_versions "$stop_release" "$upgrade_release" ) > /dev/null
+        ret="$?"
+        case "$ret" in
+        1)
+          echo "Notice: Upgrading from $installed_release to $upgrade_release would omit installing $stop_release as a stop release!" >&2
+          if [ -n "$set_ssu" ]
+          then echo "Thus upgrading to $stop_release instead." >&2
+            else
+            echo -n "Set SSU to $stop_release before upgrading (a negative reply aborts)?" >&2
+            askyes >&2
+            set_ssu="yes"
+          fi
+          upgrade_release="$stop_release"
+          echo >&2
+          break
+          ;;
+        [02]) # A general downgrade check is performed later; this solely deals with downgrading "below" stop releases (here: "or not").
+          break
+          ;;
+        *)
+          echo "Comparing versions in \"stop releases\" check failed." >&2
+          exit "$ret"
+          ;;
+        esac
+        ;;
+      *)
+        echo "Comparing versions in \"stop releases\" check #2 failed." >&2
+        exit "$ret"
+        ;;
+      esac
+    done
+    ;;
+  2)  # Downgrade
+    # Iterating downwards through all stop releases:
+    for stop_release in $(echo "$all_stop_releases" | sort -r)
+    do
+      # A general downgrade check is performed later; this solely deals with downgrading "below" stop releases.
+      field="$(( compare_versions "$stop_release" "$installed_release" ); ret="$?")"
+      case "${ret}-$field" in
+      2-?)
+        true
+        ;;
+      [01]-?)  # Hit the first stop release, which is lesser or equal to the installed release.
+        field="$(( compare_versions "$stop_release" "$upgrade_release" ); ret="$?")"
+        case "${ret}-$field" in
+        [01]-?)  # A general downgrade check is performed later; this solely deals with downgrading "below" stop releases (here: "or not").
+          break
+          ;;
+        2-4)
+          echo "Warning: About to DOWNGRADE SailfishOS from $installed_release to ${upgrade_release}, which downgrades to a \"point release\" \"below\" the stop release $stop_release." >&2
+          echo "While downgrading between \"point releases\" seems to be generally feasible, doing so \"below\" a stop release bears the little extra danger of the changes making it a stop release not all being introduced with SailfishOS $(echo "$stop_release" | cut -f -3 -d '.').0 (e.g. with ${stop_release}, and thus potentially downgrading \"across\" these changes, which would break this SailfishOS installation)." >&2
+          echo "The only absolutely safe way to achieve this is to execute a \"factory reset\", followed by UPgrading to the intended version.  Although one may try downgrading and if it fails or breaks some functionality, perform a \"factory reset\" (in the worst case at the recovery console)." >&2
+          echo >&2
+          break
+          ;;
+        2-?)
+          echo "Aborting: Trying to DOWNGRADE SailfishOS from $installed_release to ${upgrade_release}, which is \"across\" the stop release ${stop_release}!" >&2
+          echo "Doing that would likely break this SailfishOS installation." >&2
+          echo "The only way to achieve this properly is to execute a \"factory reset\", followed by UPgrading to the intended version." >&2
+          exit 3
+          ;;
+        *)
+          echo "Comparing versions in \"stop releases\" check failed." >&2
+          exit "$ret"
+          ;;
+        esac
+        ;;
+      2-4)
+        field="$(( compare_versions "$stop_release" "$upgrade_release" ); ret="$?")"
+        case "${ret}-$field" in
+        [01]-?)
+          echo "Noticed a harmless internal logical mistake!" >&2
+          echo >&2
+          break
+          ;;
+        2-4)
+          echo "Warning: About to DOWNGRADE SailfishOS from $installed_release to ${upgrade_release}, which downgrades to a \"point release\" \"within\" the stop release range $(echo "$stop_release" | cut -f -3 -d '.').x!" >&2
+          echo "While downgrading between \"point releases\" seems to be generally feasible, doing so \"below\" a stop release bears the little extra danger of the changes making it a stop release not all being introduced with SailfishOS $(echo "$stop_release" | cut -f -3 -d '.').0 (e.g. with ${installed_release}, and hence potentially downgrading \"across\" these changes, which would break this SailfishOS installation)." >&2
+          echo "The only absolutely safe way to achieve this is to execute a \"factory reset\", followed by UPgrading to the intended version.  Although one may try downgrading and if it fails or breaks some functionality, perform a \"factory reset\" (in the worst case at the recovery console)." >&2
+          echo >&2
+          break
+          ;;
+        2-?)
+          echo "Aborting: Trying to DOWNGRADE SailfishOS from $installed_release to ${upgrade_release}, which is \"across\" the stop release ${stop_release}!" >&2
+          echo "Doing that would likely break this SailfishOS installation." >&2
+          echo "The only way to achieve this properly is to execute a \"factory reset\", followed by UPgrading to the intended version." >&2
+          exit 3
+          ;;
+        *)
+          echo "Comparing versions in \"stop releases\" check failed." >&2
+          exit "$ret"
+          ;;
+        esac
+        ;;
+      *)
+        echo "Comparing versions in \"stop releases\" check #4 failed." >&2
+        exit "$ret"
+        ;;
+      esac
+    done
     ;;
   *)
-    echo "Comparing versions in \"stop releases\" check failed." >&2
+    echo "Comparing versions in \"stop releases\" check #1 failed." >&2
     exit "$ret"
     ;;
   esac
-done
+fi
 
 if mount -t btrfs | cut -s -f 3 -d ' ' | grep -q '^/$'
 then
