Update sfos-upgrade

diff --git a/usr/bin/sfos-upgrade b/usr/bin/sfos-upgrade
--- a/usr/bin/sfos-upgrade
+++ b/usr/bin/sfos-upgrade
@@ -128,7 +128,7 @@ else
     exit 2
     ;;
   *)
-    echo "Aborting: Inorrect version format \"${upgrade_release}\" provided." >&2
+    echo "Aborting: Incorrect version format \"${upgrade_release}\" provided." >&2
     exit 3
     ;;
   esac
