Update sfos-upgrade

diff --git a/usr/bin/sfos-upgrade b/usr/bin/sfos-upgrade
--- a/usr/bin/sfos-upgrade
+++ b/usr/bin/sfos-upgrade
@@ -70,8 +70,12 @@ fi
 KNOWNSTOPVERSIONS="3.0.0.8\n2.2.0.29\n2.0.0.10\n1.1.9.30\n1.1.7.28\n1.1.2.16\n1.0.2.5"
 # 0.99.5.11, 1.0.0.5 and 1.0.1.10 are not documented to be "stop releases", taking the information of sections 4 and 5 (in combination!)
 # into account: https://jolla.zendesk.com/hc/en-us/articles/201836347#4
-STOPVERSIONS="$(curl -sS https://jolla.zendesk.com/hc/en-us/articles/201836347 | sed -n '/id="4"/,/id="5"/p' | sed -n '/<ul>/,/<\/ul>/p' | sed -n '/<li>/,/<\/li>/p' | tr '\200-\377' ' ' | cut -f 2- -d '>' | rev | cut -f 2- -d '<' | rev | cut -f 1 -d ' ' | tr -cd '0-9.\n')\n$KNOWNSTOPVERSIONS"
-for i in $(echo -e "$STOPVERSIONS" | egrep '^[1-9]\.[0-9]\.[0-9]\.[0-9]$|^[1-9]\.[0-9]\.[0-9]\.[0-9][0-9]$' | sort -u)
+if ! STOPVERSIONS="$(curl -sS https://jolla.zendesk.com/hc/en-us/articles/201836347 | sed -n '/id="4"/,/id="5"/p' | sed -n '/<ul>/,/<\/ul>/p' | sed -n '/<li>/,/<\/li>/p' | sed 's/<[^>]*>/\n/g' | tr -c '.0-9' '\n' | egrep '^[1-9]\.[0-9]\.[0-9]\.[0-9]$|^[1-9]\.[0-9]\.[0-9]\.[0-9][0-9]$')\n$KNOWNSTOPVERSIONS"
+then
+  echo "Warning: Failed to extract recent \"stop releases\" from https://jolla.zendesk.com/hc/en-us/articles/201836347#4"
+  echo
+fi
+for i in $(echo -e "$STOPVERSIONS" | sort -u)
 do
   if expr "$OLDVERSION" "<" "$i" > /dev/null && expr "$NEWVERSION" ">" "$i" > /dev/null && true
   then
