Update sfos-upgrade

diff --git a/usr/bin/sfos-upgrade b/usr/bin/sfos-upgrade
--- a/usr/bin/sfos-upgrade
+++ b/usr/bin/sfos-upgrade
@@ -154,6 +154,7 @@ else
     echo >&2
     ;;
   *)
+    echo "Comparing versions in check for the installed version differing from the one currently set for SSU failed." >&2
     exit "$ret"
     ;;
   esac
@@ -194,8 +195,8 @@ then
   fi
   all_stop_releases="$(echo -e "${recent_stop_releases}\n$known_stop_releases" | grep -v '^$' | sort -u)"
   ( compare_versions "$installed_release" "$upgrade_release" ) > /dev/null
-  ret="$?"
-  case "$ret" in
+  ret0="$?"
+  case "$ret0" in
   0)  # Equality
     echo "Noticed a harmless internal logical mistake: Equality was tested before!" >&2
     echo >&2
@@ -205,15 +206,15 @@ then
     for stop_release in $all_stop_releases
     do
       ( compare_versions "$stop_release" "$installed_release" ) > /dev/null
-      ret="$?"
-      case "$ret" in
+      ret1="$?"
+      case "$ret1" in
       [01])
         true
         ;;
       2)  # Hit the first stop release, which is greater than the installed release.
         ( compare_versions "$stop_release" "$upgrade_release" ) > /dev/null
-        ret="$?"
-        case "$ret" in
+        ret2="$?"
+        case "$ret2" in
         1)
           echo "Notice: Upgrading from $installed_release to $upgrade_release would omit installing $stop_release as a stop release!" >&2
           if [ -n "$set_ssu" ]
@@ -231,14 +232,14 @@ then
           break
           ;;
         *)
-          echo "Comparing versions in \"stop releases\" check failed." >&2
-          exit "$ret"
+          echo "Comparing versions in \"stop releases\" check #2a failed." >&2
+          exit "$ret2"
           ;;
         esac
         ;;
       *)
-        echo "Comparing versions in \"stop releases\" check #2 failed." >&2
-        exit "$ret"
+        echo "Comparing versions in \"stop releases\" check #1a failed." >&2
+        exit "$ret1"
         ;;
       esac
     done
@@ -248,14 +249,14 @@ then
     for stop_release in $(echo "$all_stop_releases" | sort -r)
     do
       # A general downgrade check is performed later; this solely deals with downgrading "below" stop releases.
-      field="$( ( compare_versions "$stop_release" "$installed_release" ); ret="$?")"
-      case "${ret}-$field" in
+      field1="$( ( compare_versions "$stop_release" "$installed_release" ); ret1="$?")"
+      case "${ret1}-$field1" in
       2-?)
         true
         ;;
       [01]-?)  # Hit the first stop release, which is lesser or equal to the installed release.
-        field="$(( compare_versions "$stop_release" "$upgrade_release" ); ret="$?")"
-        case "${ret}-$field" in
+        field2="$(( compare_versions "$stop_release" "$upgrade_release" ); ret2="$?")"
+        case "${ret2}-$field2" in
         [01]-?)  # A general downgrade check is performed later; this solely deals with downgrading "below" stop releases (here: "or not").
           break
           ;;
@@ -273,14 +274,14 @@ then
           exit 3
           ;;
         *)
-          echo "Comparing versions in \"stop releases\" check failed." >&2
-          exit "$ret"
+          echo "Comparing versions in \"stop releases\" check #2b failed." >&2
+          exit "$ret2"
           ;;
         esac
         ;;
       2-4)
-        field="$( ( compare_versions "$stop_release" "$upgrade_release" ); ret="$?")"
-        case "${ret}-$field" in
+        field2="$( ( compare_versions "$stop_release" "$upgrade_release" ); ret2="$?")"
+        case "${ret2}-$field2" in
         [01]-?)
           echo "Noticed a harmless internal logical mistake!" >&2
           echo >&2
@@ -300,21 +301,21 @@ then
           exit 3
           ;;
         *)
-          echo "Comparing versions in \"stop releases\" check failed." >&2
-          exit "$ret"
+          echo "Comparing versions in \"stop releases\" check #2c failed." >&2
+          exit "$ret2"
           ;;
         esac
         ;;
       *)
-        echo "Comparing versions in \"stop releases\" check #4 failed." >&2
-        exit "$ret"
+        echo "Comparing versions in \"stop releases\" check #1b failed." >&2
+        exit "$ret1"
         ;;
       esac
     done
     ;;
   *)
-    echo "Comparing versions in \"stop releases\" check #1 failed." >&2
-    exit "$ret"
+    echo "Comparing versions in \"stop releases\" check #0 failed." >&2
+    exit "$ret0"
     ;;
   esac
 fi
