Adjusting "Adjust free space limits"
Readjusting the minimal free space limit for the root file-system to soften it slightly compared to commit #3918a11

diff --git a/usr/bin/sfos-upgrade b/usr/bin/sfos-upgrade
--- a/usr/bin/sfos-upgrade
+++ b/usr/bin/sfos-upgrade
@@ -390,14 +390,14 @@ then
   fi
 else
   free_space="$(df -k / | sed -n '2p' | rev | grep '^/ ' | tr -s ' ' | cut -s -f 3 -d ' ' | rev)"
-  if ! [ "$free_space" -ge "786432" ]
+  if ! [ "$free_space" -ge "699050" ]
   then
-    echo "Aborting: Less than 0.75 GiB ($free_space KiB) of free space on the root filesystem!" >&2
+    echo "Aborting: Less than ⅔ GiB ($free_space KiB) free space on the root filesystem!" >&2
     echo "Please clean up or enlarge the root filesystem before retrying." >&2
     exit 1
   elif ! [ "$free_space" -ge "1048576" ]
   then
-    echo "Warning: Less than 1 GiB ($free_space KiB) of free space on the root filesystem!" >&2
+    echo "Warning: Less than 1 GiB ($free_space KiB) free space on the root filesystem!" >&2
     echo "Please consider to abort and to clean up or enlarge the root filesystem before retrying." >&2
     echo >&2
   fi
