Update sfos-upgrade (#28)
* Introduce downgrade check "below" a stop release

* Update sfos-upgrade

* Update sfos-upgrade

* Update sfos-upgrade

* Update sfos-upgrade

* Update sfos-upgrade

* Update sfos-upgrade

* Update sfos-upgrade

* Update sfos-upgrade

diff --git a/usr/bin/sfos-upgrade b/usr/bin/sfos-upgrade
--- a/usr/bin/sfos-upgrade
+++ b/usr/bin/sfos-upgrade
@@ -184,24 +184,37 @@ do
   ( compare_versions "$stop_release" "$installed_release" ) > /dev/null
   ret="$?"
   case "$ret" in
-  1|0)
-    ( compare_versions "$stop_release" "$upgrade_release" ) > /dev/null
-    ret="$?"
-    if [ "$ret" = "2" ]
-    then
+  [01])
+    # A general downgrade check is performed later; this solely deals with downgrading "below" stop releases.
+    field="$(( compare_versions "$stop_release" "$upgrade_release" ); ret="$?")"
+    case "${ret}-$field" in
+    [01]-?)
+      true
+      ;;
+    2-4)
+      echo "Warning: About to DOWNGRADE SailfishOS from $installed_release to ${upgrade_release}, which downgrades \"below\" the stop release $stop_release." >&2
+      echo "While downgrading between \"point releases\" seems to be generally feasible, doing so \"below\" a stop release bears the little extra danger of the changes making it a stop release not all being introduced with SailfishOS $(echo "$stop_release" | cut -f -3 -d '.').0 (e.g. with $stop_release and thus potentially downgrading \"across\" these changes, which would break this SailfishOS installation)." >&2
+      echo "The only absolutely safe way to achieve this is to execute a \"factory reset\", followed by UPgrading to the intended version.  Although one may try downgrading and if it fails or breaks some functionality, perform a \"factory reset\" (in the worst case at the recovery console)." >&2
+      echo >&2
+      break
+      ;;
+    2-?)
       echo "Aborting: Trying to DOWNGRADE SailfishOS from $installed_release to ${upgrade_release}, which is \"across\" the stop release ${stop_release}!" >&2
-      echo "Doing that would likely make this SailfishOS installation unusable." >&2
+      echo "Doing that would likely break this SailfishOS installation." >&2
       echo "The only way to achieve this properly is to execute a \"factory reset\", followed by UPgrading to the intended version." >&2
       exit 3
-    elif [ "$ret" -gt "2" ]
-    then exit "$ret"
-    fi
+      ;;
+    *)
+      echo "Comparing versions in \"stop releases\" check failed." >&2
+      exit "$ret"
+      ;;
+    esac
     ;;
   2)
     ( compare_versions "$stop_release" "$upgrade_release" ) > /dev/null
     ret="$?"
-    if [ "$ret" = "1" ]
-    then
+    case "$ret" in
+    1)
       echo "Notice: Upgrading from $installed_release to $upgrade_release would omit installing $stop_release as a stop release!" >&2
       if [ -n "$set_ssu" ]
       then echo "Thus upgrading to $stop_release instead." >&2
@@ -213,11 +226,19 @@ do
       upgrade_release="$stop_release"
       echo >&2
       break
-    elif [ "$ret" -gt "2" ]
-    then exit "$ret"
-    fi
+      ;;
+    [02])
+      # A general downgrade check is performed later; this solely deals with downgrading "below" stop releases (here: "or not").
+      break
+      ;;
+    *)
+      echo "Comparing versions in \"stop releases\" check failed." >&2
+      exit "$ret"
+      ;;
+    esac
     ;;
   *)
+    echo "Comparing versions in \"stop releases\" check failed." >&2
     exit "$ret"
     ;;
   esac
@@ -458,29 +479,34 @@ case "$ret" in
     echo "Notice: About to DOWNGRADE SailfishOS from $installed_release to ${upgrade_release}, which just carries a smaller \"point release\" number." >&2
     echo "Nevertheless this may make this SailfishOS installation not working properly." >&2
     echo "Note that the "official" (i.e. approved by Jolla) way to achieve this is to execute a \"factory reset\", followed by UPgrading to the intended version." >&2
+    echo "Though you can try downgrading and if it fails or breaks some functionality, perform a \"factory reset\" then (in the worst case at the recovery console)." >&2
     echo -n "Do you want to do that?" >&2
     ;;
   4?*)
     echo "Warning: About to DOWNGRADE SailfishOS from $installed_release to ${upgrade_release}, which just carries a smaller \"point release\" number." >&2
     echo "Nevertheless this may make this SailfishOS installation not working properly." >&2
     echo "Note that the "official" (i.e. approved by Jolla) way to achieve this is to execute a \"factory reset\", followed by UPgrading to the intended version." >&2
+    echo "Though you may try downgrading and if it fails or breaks some functionality, perform a \"factory reset\" then (in the worst case at the recovery console)." >&2
     echo -n "Do you really want to do that?" >&2
     ;;
   ?)
     echo "Warning: About to DOWNGRADE SailfishOS from $installed_release to ${upgrade_release}." >&2
     echo "This might make this SailfishOS installation not working properly!" >&2
     echo "Note that the proper way to achieve this is to execute a \"factory reset\", followed by UPgrading to the intended version." >&2
+    echo "Although you may try downgrading and if it fails or breaks some functionality, perform a \"factory reset\" then (in the worst case at the recovery console)." >&2
     echo -n "Do you really want to do that?" >&2
     ;;
   *)
     echo "Aborting: Trying to DOWNGRADE SailfishOS from $installed_release to ${upgrade_release}!" >&2
-    echo "Though this might make this SailfishOS installation not working properly, this downgrade can be performed by setting SSU to the intended release before starting sfos-upgrade without a parameter." >&2
+    echo "Though this might make this SailfishOS installation not working properly, this downgrade may be performed by setting SSU to the intended release before starting sfos-upgrade without a parameter." >&2
     echo "Note that the proper way to achieve this is to execute a \"factory reset\", followed by UPgrading to the intended version." >&2
+    echo "Although you may try downgrading and if it fails or breaks some functionality, perform a \"factory reset\" then (in the worst case at the recovery console)."
     exit 3
     ;;
   esac
   ;;
 *)
+  echo "Comparing versions failed, when asking user to finally perform up-, same- or down-grading SailfishOS." >&2
   exit "$ret"
   ;;
 esac
@@ -590,7 +616,9 @@ then
   done
   echo | tee -a "$logfile" >&2
 elif [ "$ret" -gt "2" ]
-then exit "$ret"
+then
+  echo "Comparing versions in \"upgrading from below SailfishOS 1.0.4.20\" check failed." >&2
+  exit "$ret"
 fi
 
 if [ -n "$set_ssu" ]
