Update sfos-upgrade

diff --git a/usr/bin/sfos-upgrade b/usr/bin/sfos-upgrade
--- a/usr/bin/sfos-upgrade
+++ b/usr/bin/sfos-upgrade
@@ -3,7 +3,7 @@ set -o posix
 set -eufC
 
 # Switched to use bash since version 2.1 of this script (in its first two lines), as this ensures that -o pipefail
-# (in line 605) is available, after checking that bash seems to be present in mer-core at least since 2011-10-04 (see
+# (in line 604) is available, after checking that bash seems to be present in mer-core at least since 2011-10-04 (see
 # https://git.merproject.org/mer-core/bash ) and consequently in SailfishOS since its beginnings (checked v1.0.0.5 per
 # curl https://releases.sailfishos.org/sources/sailfish-1.0.0.5-oss.tar.bz2 | tar -tv | fgrep 'bash' , as no earlier
 # released version is available there, e.g. the first ones at https://coderus.openrepos.net/whitesoft/sailversion ).
@@ -63,26 +63,25 @@ compare_versions ()
     version_a="$1"
     version_b="$2"
     retc=0
-    comparison="e"
     for field_num in 1 2 3 4
     do
       a_substring="$(echo "$version_a" | cut -s -f "$field_num" -d '.')"
       b_substring="$(echo "$version_b" | cut -s -f "$field_num" -d '.')"
-      if [ "$a_substring" != "$b_substring" ]
+      if [ "$a_substring" = "$b_substring" ]
       then
-        if [ "$a_substring" -lt "$b_substring" ]
-        then
-          comparison="l"
-          break
-        elif [ "$a_substring" -gt "$b_substring" ]
-        then
-          comparison="g"
-          break
-        else
-          echo "Aborting due to internal error in function compare_versions: Version strings \"${version_a}\" and \"${version_b}\" are not comparable!" >&2
-          retc=3
-          break
-        fi
+        comparison="e"
+      elif [ "$a_substring" -lt "$b_substring" ]
+      then
+        comparison="l"
+        break
+      elif [ "$a_substring" -gt "$b_substring" ]
+      then
+        comparison="g"
+        break
+      else
+        echo "Aborting due to internal error in function compare_versions: Version strings \"${version_a}\" and \"${version_b}\" are not comparable!" >&2
+        retc=3
+        break
       fi
     done
     echo "$comparison$field_num"
