Add files via upload

diff --git a/usr/bin/sfos-upgrade b/usr/bin/sfos-upgrade
--- a/usr/bin/sfos-upgrade
+++ b/usr/bin/sfos-upgrade
@@ -65,44 +65,85 @@ fi
 FREESPACE="$(df -k / | sed -n 2p | rev | grep '^/ ' | tr -s ' ' | cut -f 3 -d ' ' | rev)"
 if [ "$FREESPACE" -lt "1000000" ]
 then
-  echo "Less than 1 GByte ($FREESPACE KBytes) of free space on root filesystem: Aborting!"
+  echo "Less than 1 GB ($FREESPACE KB) of free space on root filesystem: aborting!"
   echo "Please clean up before retrying."
   exit 1
 fi
 if [ "$FREESPACE" -lt "1500000" ]
 then
-  echo "Less than 1,5 GByte ($FREESPACE KBytes) of free space on root filesystem!"
+  echo "Less than 1,5 GB ($FREESPACE KB) of free space on root filesystem!"
   echo "Please consider to abort and to clean up before retrying."
   echo
 fi
 if mount -t btrfs | cut -f 3 -d ' ' | grep -q '^/$'
 then
-  BTRFSALLOC="$(btrfs-balancer allocation / | tr -s ' ')"
-  ALLOCATION=$(echo "$BTRFSALLOC" | fgrep 'Allocated: ' | cut -f 2 -d ' ')
-  if [ "$ALLOCATION" -ge "90" ]
+  BTRFSTEST="ok"
+  if which btrfs-balancer > /dev/null
   then
-    echo "Allocation (${ALLOCATION}%) of BTRFS root filesystem is 90% or more: Aborting!"
-    echo "Please perform a btrfs-balancer run before retrying."
+    BTRFSALLOC="$(btrfs-balancer allocation / | tr -s ' ')"
+    ALLOCATION=$(echo "$BTRFSALLOC" | fgrep 'Allocated: ' | cut -f 2 -d ' ')
+    if [ "$ALLOCATION" -ge "90" ]
+    then
+      echo "Allocation (${ALLOCATION}%) of BTRFS root filesystem is 90% or more: aborting!"
+      echo "Please perform a btrfs-balancer run before retrying."
+      exit 1
+    fi
+    if [ "$ALLOCATION" -ge "85" ]
+    then
+      echo "Allocation (${ALLOCATION}%) of BTRFS root filesystem is 85% or more!"
+      echo "Please consider to abort and to perform a btrfs-balancer run before retrying."
+      echo
+    fi
+    BTRFSTOTAL=$(echo "$BTRFSALLOC" | fgrep 'Total: ' | cut -f 2 -d ' ')
+    BTRFSUSED=$(echo "$BTRFSALLOC" | fgrep 'Used: ' | cut -f 2 -d ' ')
+    if UNALLOCSPC=$(expr "$BTRFSTOTAL" "-" "$BTRFSUSED")
+    then
+      if [ "1500000000" -gt "$UNALLOCSPC" ]
+      then
+        echo "Less than 1,5 GiB unallocated space ($UNALLOCSPC Bytes) on BTRFS root filesystem: aborting!"
+        echo "Please perform a btrfs-balancer run before retrying."
+        exit 1
+      fi
+      if [ "2000000000" -gt "$UNALLOCSPC" ]
+      then
+        echo "Less than 2 GiB unallocated space ($UNALLOCSPC Bytes) on BTRFS root filesystem!"
+        echo "Please consider to abort and to perform a btrfs-balancer run before retrying."
+        echo
+      fi
+    else
+      BTRFSTEST="KO"
+    fi
+  else
+    if which btrfs > /dev/null
+    then
+      BTRFSALLOC="$(btrfs filesystem df / | grep '^Data, ' | cut -f 2 -d ':' | sed 's/,/\n/g' | tr -d ' ' | rev | grep '^Bi*G[0-9][0-9]\.[0-9][0-9]*=' | sed 's/^Gi*B//g' | tr -d '.' | rev)"
+      BTRFSTOTAL=$(echo "$BTRFSALLOC" | fgrep 'total=' | cut -f 2 -d '=')
+      BTRFSUSED=$(echo "$BTRFSALLOC" | fgrep 'used=' | cut -f 2 -d '=')
+      if UNALLOCSPC=$(expr "$BTRFSTOTAL" "-" "$BTRFSUSED")
+      then
+        if [ "$UNALLOCSPC" -lt "150" ]
+        then
+          echo "Less than 1,5 GiB unallocated space ($(echo $UNALLOCSPC | rev | cut -c 3- | rev),$(echo $UNALLOCSPC | rev | cut -c 1-2 | rev) GiB) on BTRFS root filesystem: aborting!"
+          echo "Please perform a btrfs-balancer run before retrying."
+          exit 1
+        fi
+        if [ "$UNALLOCSPC" -lt "200" ]
+        then
+          echo "Less than 2 GiB unallocated space ($(echo $UNALLOCSPC | rev | cut -c 3- | rev),$(echo $UNALLOCSPC | rev | cut -c 1-2 | rev) GiB) on BTRFS root filesystem!"
+          echo "Please consider to abort and to perform a btrfs-balancer run before retrying."
+          echo
+        fi
+      else
+        BTRFSTEST="KO"
+      fi
+    else
+      BTRFSTEST="KO"
+    fi
+  fi
+  if [ "$BTRFSTEST" = "KO" ]
+  then
+    echo "Cannot properly determine allocation of BTRFS root filesystem: aborting."
     exit 1
-  fi
-  if [ "$ALLOCATION" -ge "85" ]
-  then
-    echo "Allocation (${ALLOCATION}%) of BTRFS root filesystem is 85% or more!"
-    echo "Please consider to abort and to perform a btrfs-balancer run before retrying."
-    echo
-  fi
-  UNALLOCSPC=$(expr $(echo "$BTRFSALLOC" | fgrep 'Total: ' | cut -f 2 -d ' ') "-" $(echo "$BTRFSALLOC" | fgrep 'Used: ' | cut -f 2 -d ' '))
-  if [ "$UNALLOCSPC" -lt "1500000000" ]
-  then
-    echo "Less than 1,5 GByte of unallocated space ($UNALLOCSPC Bytes) on BTRFS root filesystem: Aborting!"
-    echo "Please perform a btrfs-balancer run before retrying."
-    exit 1
-  fi
-  if [ "$UNALLOCSPC" -lt "2000000000" ]
-  then
-    echo "Less than 2 GByte of unallocated space ($UNALLOCSPC Bytes) on BTRFS root filesystem!"
-    echo "Please consider to abort and to perform a btrfs-balancer run before retrying."
-    echo
   fi
 fi
 
