Update sfos-upgrade

diff --git a/usr/bin/sfos-upgrade b/usr/bin/sfos-upgrade
--- a/usr/bin/sfos-upgrade
+++ b/usr/bin/sfos-upgrade
@@ -194,7 +194,8 @@ then
   ret0="$?"
   case "$ret0" in
   0)  # Equality
-    echo "Noticed a harmless internal logical mistake: Equality was tested before!" >&2
+    echo "Noticed a supposedly harmless internal logical mistake: Equality was tested before!" >&2
+    echo "Hence carrying on." >&2
     echo >&2
     ;;
   1)  # Upgrade
@@ -279,7 +280,8 @@ then
         field2="$( ( compare_versions "$stop_release" "$upgrade_release" ); ret2="$?")"
         case "${ret2}-$field2" in
         [01]-?)
-          echo "Noticed a harmless internal logical mistake!" >&2
+          echo "Noticed a supposedly harmless internal logical mistake!" >&2
+          echo "Hence carrying on." >&2
           echo >&2
           break
           ;;
@@ -562,14 +564,14 @@ case "$ret_u" in
     echo -n "Do you really want to do that?" >&2
     ;;
   ?)
-    echo "Warning: About to DOWNGRADE SailfishOS from $installed_release to ${upgrade_release}." >&2
+    echo "Warning: About to DOWNGRADE SailfishOS from $installed_release to ${upgrade_release}, which differ in at least their minor version." >&2
     echo "This might make this SailfishOS installation not working properly!" >&2
     echo "Note that the proper way to achieve this is to execute a \"factory reset\", followed by UPgrading to the intended version." >&2
     echo "Although you may try downgrading and if it fails or breaks some functionality, perform a \"factory reset\" then (in the worst case at the recovery console)." >&2
     echo -n "Do you really want to do that?" >&2
     ;;
   *)
-    echo "Aborting: Trying to DOWNGRADE SailfishOS from $installed_release to ${upgrade_release}!" >&2
+    echo "Aborting: Trying to DOWNGRADE SailfishOS from $installed_release to ${upgrade_release}, which differ in at least their minor version!" >&2
     echo "Though this might make this SailfishOS installation not working properly, this downgrade may be performed by setting SSU to the intended release before starting sfos-upgrade without a parameter." >&2
     echo "Note that the proper way to achieve this is to execute a \"factory reset\", followed by UPgrading to the intended version." >&2
     echo "Although you may try downgrading and if it fails or breaks some functionality, perform a \"factory reset\" then (in the worst case at the recovery console)."
