Improvements and enhancements for v3.0 (#25)
* Update sfos-upgrade

* Update sfos-upgrade

* Update sfos-upgrade

* Update sfos-upgrade

* Update sfos-upgrade

* Update sfos-upgrade

* Update sfos-upgrade

* Update sfos-upgrade

* Update sfos-upgrade

* Update sfos-upgrade

* Update sfos-upgrade

* Update sfos-upgrade

* Update sfos-upgrade

* Strip trailing spaces

diff --git a/usr/bin/sfos-upgrade b/usr/bin/sfos-upgrade
--- a/usr/bin/sfos-upgrade
+++ b/usr/bin/sfos-upgrade
@@ -3,7 +3,7 @@ set -o posix
 set -eufC
 
 # Switched to use bash since version 2.1 of this script (in its first two lines), as this ensures that -o pipefail
-# (in line 349) is available, after checking that bash seems to be present in mer-core at least since 2011-10-04 (see
+# (in line 416) is available, after checking that bash seems to be present in mer-core at least since 2011-10-04 (see
 # https://git.merproject.org/mer-core/bash ) and consequently in SailfishOS since its beginnings (checked v1.0.0.5 per
 # curl https://releases.sailfishos.org/sources/sailfish-1.0.0.5-oss.tar.bz2 | tar -tv | fgrep 'bash' , as no earlier
 # released version is available there, e.g. the first ones at https://coderus.openrepos.net/whitesoft/sailversion ).
@@ -19,8 +19,9 @@ set -eufC
 #   4  Aborted upon user interaction
 #   5  Error while interacting with the OS (reading / writing from the filesystem, calling programs, etc.)
 #   6  Error while executing one of the preparatory steps for the upgrade proper
-#  23  "Should never be reached" *) case #1
-#  42  "Should never be reached" *) case #2
+#  13  "Should never be reached" *) case #1
+#  23  "Should never be reached" *) case #2
+#  42  "Should never be reached" *) case #3
 
 export LC_CTYPE="POSIX"
 export LC_COLLATE="POSIX"
@@ -38,6 +39,47 @@ askyes ()
     exit 4
     ;;
   esac
+  if [ -n "$*" ]
+  then
+    echo "Notice: No parameters expected, but set: $*"
+    return 1
+  else
+    return 0
+  fi
+}
+
+compare_versions ()
+{
+  # Returns 0 if A = B, 1 if A < B, 2 if A > B, 3 if incomparable, and 4 if not called with two parameters
+  if [ "$#" -ne "2" ]
+  then
+    echo "Error: Two parameters expected, but $# received!"
+    return 4
+  fi
+  version_a="$1"
+  version_b="$2"
+  for i in 1 2 3 4
+  do
+    a_substring="$(echo "$version_a" | cut -s -f "$i" -d '.')"
+    b_substring="$(echo "$version_b" | cut -s -f "$i" -d '.')"
+    if [ "$a_substrimg" = "$b_substring" ]
+    then
+      ret=0
+    elif [ "$a_substring" -lt "$b_substring" ]
+    then
+      ret=1
+      break
+    elif [ "$a_substring" -gt "$b_substring" ]
+    then
+      ret=2
+      break
+    else
+      ret=3
+      echo "Error: Version strings are not comparable!"
+      break
+    fi
+  done
+  return "$ret"
 }
 
 called="$(basename "$0")"
@@ -47,7 +89,7 @@ then
   exit 3
 fi
 
-installed_release="$(version | rev | cut -f 2 -d ' ' | rev)"
+installed_release="$(version | rev | cut -s -f 2 -d ' ' | rev)"
 if [ -z "$*" ]
 then
   set_ssu=""
@@ -81,7 +123,7 @@ else
   then
     echo "Notice: The installed version $installed_release differs from the one currently set for SSU (${ssu_set})."
     echo "A possible reason for this is, that the \'sailfish-osupdateservice osupdate-check\' invoked by osupdate-check.service"
-    echo "(which is regularly triggered by osupdate-check.timer) and maybe also by the store-client seems to do more than just checking"
+    echo "(which is regularly triggered by osupdate-check.timer) does more than just checking (in SailfishOS 3.0.2 and earlier)"
     echo "(e.g., setting ssu to the recent release version or next stop release)."
     echo "Never mind, the version for SSU will be set correctly again, later on."
     echo
@@ -97,8 +139,8 @@ then
 elif ! echo "$sfos_releases" | grep -q "^$(echo "$upgrade_release" | sed 's/\./\\\./g')\$"
 then
   echo "Warning: \"${upgrade_release}\" does not seem to be a publicly released SailfishOS version!"
-  echo -n "Do you really want to continue?" 
-  askyes 
+  echo -n "Do you really want to continue?"
+  askyes
   echo
 fi
 
@@ -114,12 +156,12 @@ then
 fi
 for i in $(echo -e "${recent_stop_releases}\n$known_stop_releases" | grep -v '^$' | sort -u)
 do
-  if expr "$installed_release" '<' "$i" > /dev/null && expr "$upgrade_release" '>' "$i" > /dev/null && true
+  if [ "$(compare_versions "$installed_release" "$i"; echo "$?")" = "1" ] && [ "$(compare_versions "$upgrade_release" "$i"; echo "$?")" = "2" ] && true
   then
     echo "Notice: Upgrading from $installed_release to $upgrade_release would omit installing $i as a stop release!"
     if [ -n "$set_ssu" ]
     then echo "Thus upgrading to $i instead."
-    else 
+    else
      echo -n "Set SSU to $i before upgrading (a negative reply aborts)?"
      askyes
      set_ssu="yes"
@@ -130,7 +172,7 @@ do
   fi
 done
 
-if mount -t btrfs | cut -f 3 -d ' ' | grep -q '^/$'
+if mount -t btrfs | cut -s -f 3 -d ' ' | grep -q '^/$'
 then
   btrfs_check="KO"
   if which btrfs-balancer > /dev/null 2>&1
@@ -167,7 +209,7 @@ then
     fi
   elif which btrfs > /dev/null 2>&1
   then
-    btrfs_allocation="$(btrfs filesystem df / | grep '^Data, ' | cut -f 2 -d ':' | tr ',' '\n' | tr -d ' ' | rev | grep '^Bi*G[0-9][0-9]\.[0-9][0-9]*=' | sed 's/^Bi*G//g' | tr -d '.' | rev)"
+    btrfs_allocation="$(btrfs filesystem df / | grep '^Data, ' | cut -s -f 2 -d ':' | tr ',' '\n' | tr -d ' ' | rev | grep '^Bi*G[0-9][0-9]\.[0-9][0-9]*=' | sed 's/^Bi*G//g' | tr -d '.' | rev)"
     btrfs_total="$(echo "$btrfs_allocation" | grep '^total=' | cut -f 2 -d '=')"
     btrfs_used="$(echo "$btrfs_allocation" | grep '^used=' | cut -f 2 -d '=')"
     if btrfs_unallocated="$(expr "$btrfs_total" '-' "$btrfs_used")"
@@ -192,7 +234,7 @@ then
     exit 5
   fi
 else
-  free_space="$(df -k / | sed -n '2p' | rev | grep '^/ ' | tr -s ' ' | cut -f 3 -d ' ' | rev)"
+  free_space="$(df -k / | sed -n '2p' | rev | grep '^/ ' | tr -s ' ' | cut -s -f 3 -d ' ' | rev)"
   if ! [ "$free_space" -ge "524288" ]
   then
     echo "Aborting: Less than 0.5 GiB ($free_space KiB) of free space on the root filesystem!"
@@ -313,7 +355,7 @@ Charging-*-[0-9]*|Full-*-[0-9]*)
   fi
   ;;
 *)
-  exit 42
+  exit 13
   ;;
 esac
 case "$battery_check" in
@@ -342,13 +384,22 @@ then
   echo
 fi
 
-if expr "$installed_release" '>' "$upgrade_release" > /dev/null
-then
+compare_versions "$installed_release" "$upgrade_release"
+case "$?" in
+0)
+  echo -n "Notice: Do you want to ensure the completeness of this SailfishOS $upgrade_release installation?"
+  ;;
+1)
+  echo -n "Notice: Do you want to upgrade SailfishOS from $installed_release to $upgrade_release?"
+  ;;
+2)
   echo "Warning: About to DOWNGRADE SailfishOS from $installed_release to $upgrade_release!"
   echo -n "Do you really want to do that?"
-else
-  echo -n "Notice: Do you want to upgrade SailfishOS from $installed_release to $upgrade_release?"
-fi
+  ;;
+*)
+  exit 42
+  ;;
+esac
 askyes
 echo
 
@@ -442,11 +493,11 @@ then
 fi
 
 # Simplified since v2.3, because ssu dr seems to *always* return "O.K.":
-if expr "$installed_release" '<' "1.0.4.20" > /dev/null && openrepos_repos="$(ssu lr | fgrep 'openrepo')" && true
+if [ "$(compare_versions "$installed_release" "1.0.4.20"; echo "$?")" = "1" ] && openrepos_repos="$(ssu lr | fgrep 'openrepo')" && true
 then
   # Reference: https://jolla.zendesk.com/hc/en-us/articles/201836347#5
   echo "- Disabling OpenRepos' repositories:" | tee -a "$logfile"
-  for i in $(echo "$openrepos_repos" | cut -f 3 -d ' ')
+  for i in $(echo "$openrepos_repos" | cut -s -f 3 -d ' ')
   do
     echo "$i" | tee -a "$logfile"
     ssu dr "$i" 2>&1 | tee -a "$logfile"
