Add files via upload

diff --git a/usr/bin/sfos-upgrade b/usr/bin/sfos-upgrade
--- a/usr/bin/sfos-upgrade
+++ b/usr/bin/sfos-upgrade
@@ -62,28 +62,27 @@ compare_versions ()
   else
     version_a="$1"
     version_b="$2"
+    retc=0
+    comparison="e"
     for field_num in 1 2 3 4
     do
       a_substring="$(echo "$version_a" | cut -s -f "$field_num" -d '.')"
       b_substring="$(echo "$version_b" | cut -s -f "$field_num" -d '.')"
-      if [ "$a_substring" = "$b_substring" ]
+      if [ "$a_substring" != "$b_substring" ]
       then
-        comparison="e"
-        retc=0
-      elif [ "$a_substring" -lt "$b_substring" ]
-      then
-        comparison="l"
-        retc=0
-        break
-      elif [ "$a_substring" -gt "$b_substring" ]
-      then
-        comparison="g"
-        retc=0
-        break
-      else
-        echo "Aborting due to internal error in function compare_versions: Version strings \"${version_a}\" and \"${version_b}\" are not comparable!" >&2
-        retc=3
-        break
+        if [ "$a_substring" -lt "$b_substring" ]
+        then
+          comparison="l"
+          break
+        elif [ "$a_substring" -gt "$b_substring" ]
+        then
+          comparison="g"
+          break
+        else
+          echo "Aborting due to internal error in function compare_versions: Version strings \"${version_a}\" and \"${version_b}\" are not comparable!" >&2
+          retc=3
+          break
+        fi
       fi
     done
     echo "$comparison$field_num"
@@ -130,8 +129,8 @@ else
     exit 3
     ;;
   esac
-  ret_s="$(compare_versions "$installed_release" "$ssu_set")"
-  case "$ret_s" in
+  compar_s="$(compare_versions "$installed_release" "$ssu_set")"
+  case "$compar_s" in
   e?)
     true
     ;;
@@ -191,8 +190,8 @@ then
     echo >&2
   fi
   all_stop_releases="$(echo -e "${recent_stop_releases}\n$known_stop_releases" | grep -v '^$' | sort -u)"
-  ret0="$(compare_versions "$installed_release" "$upgrade_release")"
-  case "$ret0" in
+  compar0="$(compare_versions "$installed_release" "$upgrade_release")"
+  case "$compar0" in
   e?)  # Equality
     echo "Noticed a supposedly harmless internal logical mistake: Equality was tested before!" >&2
     echo "Hence carrying on." >&2
@@ -202,14 +201,14 @@ then
     # Iterating upwards through all stop releases:
     for stop_release in $all_stop_releases
     do
-      ret1="$(compare_versions "$stop_release" "$installed_release")"
-      case "$ret1" in
-      [el]?)
+      compar1="$(compare_versions "$stop_release" "$installed_release")"
+		      case "$compar1" in
+	      [el]?)
         true
         ;;
       g?)  # Hit the first stop release, which is greater than the installed release.
-        ret2="$(compare_versions "$stop_release" "$upgrade_release")"
-        case "$ret2" in
+        compar2="$(compare_versions "$stop_release" "$upgrade_release")"
+        case "$compar2" in
         l?)
           echo "Notice: Upgrading from $installed_release to $upgrade_release would omit installing $stop_release as a stop release!" >&2
           if [ -n "$set_ssu" ]
@@ -244,14 +243,14 @@ then
     for stop_release in $(echo "$all_stop_releases" | sort -r)
     do
       # A general downgrade check is performed later; this solely deals with downgrading "below" stop releases.
-      ret1="$(compare_versions "$stop_release" "$installed_release")"
-      case "$ret1" in
+      compar1="$(compare_versions "$stop_release" "$installed_release")"
+      case "$compar1" in
       g?)
         true
         ;;
       [el]?)  # Hit the first stop release, which is lesser or equal to the installed release.
-        ret2="$(compare_versions "$stop_release" "$upgrade_release")"
-        case "$ret2" in
+        compar2="$(compare_versions "$stop_release" "$upgrade_release")"
+        case "$compar2" in
         [el]?)  # A general downgrade check is performed later; this solely deals with downgrading "below" stop releases (here: "or not").
           break
           ;;
@@ -275,8 +274,8 @@ then
         esac
         ;;
       g4)
-        ret2="$(compare_versions "$stop_release" "$upgrade_release")"
-        case "$ret2" in
+        compar2="$(compare_versions "$stop_release" "$upgrade_release")"
+        case "$compar2" in
         [el]?)
           echo "Noticed a supposedly harmless internal logical mistake!" >&2
           echo "Hence carrying on." >&2
@@ -537,8 +536,8 @@ then
   echo >&2
 fi
 
-ret_u="$(compare_versions "$installed_release" "$upgrade_release")"
-case "$ret_u" in
+compar_u="$(compare_versions "$installed_release" "$upgrade_release")"
+case "$compar_u" in
 e?)
   echo -n "Notice: Do you want to ensure this SailfishOS $upgrade_release installation to be complete and up to date?" >&2
   ;;
@@ -675,8 +674,8 @@ then
 fi
 
 # Simplified since v2.3, because ssu dr seems to *always* return "O.K.":
-ret_o="$(compare_versions "$installed_release" "1.0.4.20")"
-case "$ret_o" in
+compar_o="$(compare_versions "$installed_release" "1.0.4.20")"
+case "$compar_o" in
 [eg]?)
   true
   ;;
