Update sfos-upgrade

diff --git a/usr/bin/sfos-upgrade b/usr/bin/sfos-upgrade
--- a/usr/bin/sfos-upgrade
+++ b/usr/bin/sfos-upgrade
@@ -51,35 +51,37 @@ askyes ()
 
 compare_versions ()
 {
-  # Returns 0 if A = B, 1 if A < B, 2 if A > B.
-  # The result is solely provided per return code, all error messages go directly to STDERR followed by exiting.
-  if [ "$#" -ne "2" ]
+  # Returns 0 if A = B, 1 if A < B, 2 if A > B, 3 if version strings are not comparable, and 7 if not called with two arguments.
+  # The result is solely provided per return code, all error messages go directly to STDERR.
+  if [ "$#" != "2" ]
   then
     echo "Aborting due to internal error: The function compare_versions expects two parameters, but was called with ${#}!" >&2
-    exit 7
+    ret=7
+  else
+    version_a="$1"
+    version_b="$2"
+    for field in 1 2 3 4
+    do
+      a_substring="$(echo "$version_a" | cut -s -f "$field" -d '.')"
+      b_substring="$(echo "$version_b" | cut -s -f "$field" -d '.')"
+      if [ "$a_substring" = "$b_substring" ]
+      then
+        ret=0
+      elif [ "$a_substring" -lt "$b_substring" ]
+      then
+        ret=1
+        break
+      elif [ "$a_substring" -gt "$b_substring" ]
+      then
+        ret=2
+        break
+      else
+        echo "Aborting due to internal error in function compare_versions: Version strings \"${version_a}\" and \"${version_b}\" are not comparable!" >&2
+        ret=3
+        break
+      fi
+    done
   fi
-  version_a="$1"
-  version_b="$2"
-  for field in 1 2 3 4
-  do
-    a_substring="$(echo "$version_a" | cut -s -f "$field" -d '.')"
-    b_substring="$(echo "$version_b" | cut -s -f "$field" -d '.')"
-    if [ "$a_substring" = "$b_substring" ]
-    then
-      ret=0
-    elif [ "$a_substring" -lt "$b_substring" ]
-    then
-      ret=1
-      break
-    elif [ "$a_substring" -gt "$b_substring" ]
-    then
-      ret=2
-      break
-    else
-      echo "Aborting due to internal error in function compare_versions: Version strings \"${version_a}\" and \"${version_b}\" are not comparable!" >&2
-      exit 3
-    fi
-  done
   return "$ret"
 }
 
