Update sfos-upgrade

diff --git a/usr/bin/sfos-upgrade b/usr/bin/sfos-upgrade
--- a/usr/bin/sfos-upgrade
+++ b/usr/bin/sfos-upgrade
@@ -97,12 +97,12 @@ fi
 FREESPACE="$(df -k / | sed -n 2p | rev | grep '^/ ' | tr -s ' ' | cut -f 3 -d ' ' | rev)"
 if ! [ "$FREESPACE" -ge "524288" ]
 then
-  echo "Less than 0.5 GB ($FREESPACE KB) of free space on the root filesystem: aborting!"
+  echo "Less than 0.5 GiB ($FREESPACE KiB) of free space on the root filesystem: aborting!"
   echo "Please clean up before retrying."
   exit 1
 elif ! [ "$FREESPACE" -ge "786432" ]
 then
-  echo "Less than 0.75 GB ($FREESPACE KB) of free space on the root filesystem!"
+  echo "Less than 0.75 GiB ($FREESPACE KiB) of free space on the root filesystem!"
   echo "Please consider to abort and to clean up before retrying."
   echo
 fi
@@ -129,12 +129,12 @@ then
     if UNALLOCSPC=$(expr "$BTRFSTOTAL" "-" "$BTRFSUSED")
     then
       BTRFSTEST="ok"
-      if ! [ "$UNALLOCSPC" -ge "1500000000" ]
+      if ! [ "$UNALLOCSPC" -ge "1610612736" ]
       then
         echo "Less than 1.5 GiB unallocated space ($UNALLOCSPC Bytes) on the root filesystem (BTRFS): aborting!"
         echo "Please perform a btrfs-balancer run before retrying."
         exit 1
-      elif ! [ "$UNALLOCSPC" -ge "2000000000" ]
+      elif ! [ "$UNALLOCSPC" -ge "2147483648" ]
       then
         echo "Less than 2 GiB unallocated space ($UNALLOCSPC Bytes) on the root filesystem (BTRFS)!"
         echo "Please consider to abort and to perform a btrfs-balancer run before retrying."
@@ -149,12 +149,12 @@ then
     if UNALLOCSPC=$(expr "$BTRFSTOTAL" "-" "$BTRFSUSED")
     then
       BTRFSTEST="ok"
-      if ! [ "$UNALLOCSPC" -ge "200" ]
+      if ! [ "$UNALLOCSPC" -ge "205" ]
       then
         echo "Less than 2 GiB unallocated data space ($(echo $UNALLOCSPC | rev | cut -c 3- | rev).$(echo $UNALLOCSPC | rev | cut -c 1-2 | rev) GiB) on the root filesystem (BTRFS): aborting!"
         echo "Please balance the btrfs root filesystem before retrying."
         exit 1
-      elif ! [ "$UNALLOCSPC" -ge "250" ]
+      elif ! [ "$UNALLOCSPC" -ge "256" ]
       then
         echo "Less than 2.5 GiB unallocated data space ($(echo $UNALLOCSPC | rev | cut -c 3- | rev).$(echo $UNALLOCSPC | rev | cut -c 1-2 | rev) GiB) on the root filesystem (BTRFS)!"
         echo "Please consider to abort and to balance the btrfs root filesystem before retrying."
