Update sfos-upgrade

diff --git a/usr/bin/sfos-upgrade b/usr/bin/sfos-upgrade
--- a/usr/bin/sfos-upgrade
+++ b/usr/bin/sfos-upgrade
@@ -190,11 +190,12 @@ then
   ( compare_versions "$installed_release" "$upgrade_release" ) > /dev/null
   ret="$?"
   case "$ret" in
-  0)  # Equality was tested before!
-    echo "Aborting due to internal logical mistake."
-    exit 42
+  0)  # Equality
+    echo "Noticed a harmless internal logical mistake: Equality was tested before!" >&2
+    echo >&2
     ;;
   1)  # Upgrade
+    # Iterating upwards through all stop releases:
     for stop_release in $all_stop_releases
     do
       ( compare_versions "$stop_release" "$installed_release" ) > /dev/null
@@ -203,7 +204,7 @@ then
       [01])
         true
         ;;
-      2)
+      2)  # Hit the first stop release, which is greater than the installed release.
         ( compare_versions "$stop_release" "$upgrade_release" ) > /dev/null
         ret="$?"
         case "$ret" in
@@ -230,27 +231,31 @@ then
         esac
         ;;
       *)
-        echo "Comparing versions in \"stop releases\" check failed." >&2
+        echo "Comparing versions in \"stop releases\" check #2 failed." >&2
         exit "$ret"
         ;;
       esac
     done
     ;;
   2)  # Downgrade
+    # Iterating downwards through all stop releases:
     for stop_release in $(echo "$all_stop_releases" | sort -r)
     do
-      ( compare_versions "$stop_release" "$upgrade_release" ) > /dev/null
-      ret="$?"
-      case "$ret" in
-      [01]) # A general downgrade check is performed later; this solely deals with downgrading "below" stop releases.
+      # A general downgrade check is performed later; this solely deals with downgrading "below" stop releases.
+      field="$(( compare_versions "$stop_release" "$installed_release" ); ret="$?")"
+      case "${ret}-$field" in
+      2-?)
+        true
+        ;;
+      [01]-?)  # Hit the first stop release, which is lesser or equal to the installed release.
         field="$(( compare_versions "$stop_release" "$upgrade_release" ); ret="$?")"
         case "${ret}-$field" in
-        [01]-?)
-          true
+        [01]-?)  # A general downgrade check is performed later; this solely deals with downgrading "below" stop releases (here: "or not").
+          break
           ;;
         2-4)
-          echo "Warning: About to DOWNGRADE SailfishOS from $installed_release to ${upgrade_release}, which downgrades \"below\" the stop release $stop_release." >&2
-          echo "While downgrading between \"point releases\" seems to be generally feasible, doing so \"below\" a stop release bears the little extra danger of the changes making it a stop release not all being introduced with SailfishOS $(echo "$stop_release" | cut -f -3 -d '.').0 (e.g. with $stop_release and thus potentially downgrading \"across\" these changes, which would break this SailfishOS installation)." >&2
+          echo "Warning: About to DOWNGRADE SailfishOS from $installed_release to ${upgrade_release}, which downgrades to a \"point release\" \"below\" the stop release $stop_release." >&2
+          echo "While downgrading between \"point releases\" seems to be generally feasible, doing so \"below\" a stop release bears the little extra danger of the changes making it a stop release not all being introduced with SailfishOS $(echo "$stop_release" | cut -f -3 -d '.').0 (e.g. with ${stop_release}, and thus potentially downgrading \"across\" these changes, which would break this SailfishOS installation)." >&2
           echo "The only absolutely safe way to achieve this is to execute a \"factory reset\", followed by UPgrading to the intended version.  Although one may try downgrading and if it fails or breaks some functionality, perform a \"factory reset\" (in the worst case at the recovery console)." >&2
           echo >&2
           break
@@ -267,8 +272,27 @@ then
           ;;
         esac
         ;;
-      2)
-
+      2-4)
+        field="$(( compare_versions "$stop_release" "$upgrade_release" ); ret="$?")"
+        case "${ret}-$field" in
+        [01]-?)
+          echo "Noticed a harmless internal logical mistake!" >&2
+          echo >&2
+          break
+          ;;
+        2-4)
+          echo "Warning: About to DOWNGRADE SailfishOS from $installed_release to ${upgrade_release}, which downgrades to a \"point release\" \"within\" the stop release range $(echo "$stop_release" | cut -f -3 -d '.').x!" >&2
+          echo "While downgrading between \"point releases\" seems to be generally feasible, doing so \"below\" a stop release bears the little extra danger of the changes making it a stop release not all being introduced with SailfishOS $(echo "$stop_release" | cut -f -3 -d '.').0 (e.g. with ${installed_release}, and hence potentially downgrading \"across\" these changes, which would break this SailfishOS installation)." >&2
+          echo "The only absolutely safe way to achieve this is to execute a \"factory reset\", followed by UPgrading to the intended version.  Although one may try downgrading and if it fails or breaks some functionality, perform a \"factory reset\" (in the worst case at the recovery console)." >&2
+          echo >&2
+          break
+          ;;
+        2-?)
+          echo "Aborting: Trying to DOWNGRADE SailfishOS from $installed_release to ${upgrade_release}, which is \"across\" the stop release ${stop_release}!" >&2
+          echo "Doing that would likely break this SailfishOS installation." >&2
+          echo "The only way to achieve this properly is to execute a \"factory reset\", followed by UPgrading to the intended version." >&2
+          exit 3
+          ;;
         *)
           echo "Comparing versions in \"stop releases\" check failed." >&2
           exit "$ret"
@@ -276,14 +300,14 @@ then
         esac
         ;;
       *)
-        echo "Comparing versions in \"stop releases\" check failed." >&2
+        echo "Comparing versions in \"stop releases\" check #4 failed." >&2
         exit "$ret"
         ;;
       esac
     done
     ;;
   *)
-    echo "Comparing versions in \"stop releases\" check failed." >&2
+    echo "Comparing versions in \"stop releases\" check #1 failed." >&2
     exit "$ret"
     ;;
   esac
