Disable download of recent stop releases list for now
Unfortunately downloading the list of recent stop releases from jolla.zendesk.com is not working anymore.
For details, see https://github.com/Olf0/sfos-upgrade/issues/48#issuecomment-709380565 ff.

diff --git a/usr/bin/sfos-upgrade b/usr/bin/sfos-upgrade
--- a/usr/bin/sfos-upgrade
+++ b/usr/bin/sfos-upgrade
@@ -191,17 +191,20 @@ else
   # Jolla 1 phones), thus being the oldest one widely tested to upgrade from (and Jolla may assume
   # only early developers to have ever obtained an earlier release on their Jolla 1 phones, hence
   # not mentioning 1.0.0.5 in Jolla's "official" guides as a stop release).
-  if ! recent_stop_releases="$(curl -sS https://jolla.zendesk.com/hc/en-us/articles/201836347 | sed -n '/id="4"/,/id="5"/p' | sed -n '/<ul>/,/<\/ul>/p' | sed -n '/<li>/,/<\/li>/p' | sed 's/<[^>]*>/\n/g' | tr -c '.0-9' '\n' | egrep '^[1-9]\.[0-9]\.[0-9]\.[0-9]$|^[1-9]\.[0-9]\.[0-9]\.[1-9][0-9]$')"
-  then
-    echo "Warning: Failed to extract the current \"stop releases\" from https://jolla.zendesk.com/hc/en-us/articles/201836347#4.1" >&2
-    echo "Hence using an internal, potentially outdated list of stop releases instead." >&2
-    if [ -z "$set_ssu" ]
-    then echo -n "Do you want to continue?" >&2
-    else echo -n "Do you really want to continue?" >&2
-    fi
-    askyes >&2
-    echo >&2
-  fi
+  # Unfortunately not working anymore (for details, see https://github.com/Olf0/sfos-upgrade/issues/48#issuecomment-709380565 ff.),
+  # thus disabling this safety measure against an outdated, internal list (above) for now:
+    recent_stop_releases=""
+  #if ! recent_stop_releases="$(curl -sS https://jolla.zendesk.com/hc/en-us/articles/201836347 | sed -n '/id="4"/,/id="5"/p' | sed -n '/<ul>/,/<\/ul>/p' | sed -n '/<li>/,/<\/li>/p' | sed 's/<[^>]*>/\n/g' | tr -c '.0-9' '\n' | egrep '^[1-9]\.[0-9]\.[0-9]\.[0-9]$|^[1-9]\.[0-9]\.[0-9]\.[1-9][0-9]$')"
+  #then
+  #  echo "Warning: Failed to extract the current \"stop releases\" from https://jolla.zendesk.com/hc/en-us/articles/201836347#4.1" >&2
+  #  echo "Hence using an internal, potentially outdated list of stop releases instead." >&2
+  #  if [ -z "$set_ssu" ]
+  #  then echo -n "Do you want to continue?" >&2
+  #  else echo -n "Do you really want to continue?" >&2
+  #  fi
+  #  askyes >&2
+  #  echo >&2
+  #fi
   all_stop_releases="$(echo -e "${recent_stop_releases}\n$known_stop_releases" | grep -v '^$' | sort -u)"
   compar0="$(compare_versions "$installed_release" "$upgrade_release")"
   case "$compar0" in
