Update sfos-upgrade

diff --git a/usr/bin/sfos-upgrade b/usr/bin/sfos-upgrade
--- a/usr/bin/sfos-upgrade
+++ b/usr/bin/sfos-upgrade
@@ -352,18 +352,31 @@ then
 fi
 
 emit_newline=""
-for i in 'cron.service' \
-  '--user btrfsstatuschecker.service' '--user btrfschecker.timer' '--user btrfschecker.service' '--user beforebtrfscheckertimer.service' \
-  '--user batterynotifierstatuschecker.service' '--user batterynotifier.timer' '--user batterynotifier.service' \
-  'btrfs-balancer.timer' 'btrfs-balance.service'
+for i in \
+  btrfsstatuschecker.service btrfschecker.timer btrfschecker.service beforebtrfscheckertimer.service \
+  batterynotifierstatuschecker.service batterynotifier.timer batterynotifier.service
 do
-  if systemctl status $(echo $i) > /dev/null 2>&1
+  if systemctl --user status "$i" > /dev/null 2>&1
   then
-    this_service="$(echo $i | rev | cut -f 1 -d ' ' | rev)"
-    echo "- Stopping $this_service" | tee -a "$logfile"
-    if ! systemctl stop $(echo $i) 2>&1 | tee -a "$logfile"
+    echo "- Stopping $i" | tee -a "$logfile"
+    if ! systemctl --user stop "$i" 2>&1 | tee -a "$logfile"
     then
-      echo -n "Warning: Failed to stop ${this_service}!  Continue?" | tee -a "$logfile"
+      echo -n "Warning: Failed to stop $i (user)!  Continue?" | tee -a "$logfile"
+      askyes | tee -a "$logfile"
+    fi
+    emit_newline="y"
+  fi
+done
+for i in \
+  cron.service \
+  btrfs-balancer.timer btrfs-balance.service
+do
+  if systemctl status "$i" > /dev/null 2>&1
+  then
+    echo "- Stopping $i" | tee -a "$logfile"
+    if ! systemctl stop "$i" 2>&1 | tee -a "$logfile"
+    then
+      echo -n "Warning: Failed to stop $i (system)!  Continue?" | tee -a "$logfile"
       askyes | tee -a "$logfile"
     fi
     emit_newline="y"
