Update sfos-upgrade

diff --git a/usr/bin/sfos-upgrade b/usr/bin/sfos-upgrade
--- a/usr/bin/sfos-upgrade
+++ b/usr/bin/sfos-upgrade
@@ -58,28 +58,25 @@ compare_versions ()
   fi
   version_a="$1"
   version_b="$2"
-  for i in 1 2 3 4
+  for dot in 1 2 3 4
   do
-    a_substring="$(echo "$version_a" | cut -s -f "$i" -d '.')"
-    b_substring="$(echo "$version_b" | cut -s -f "$i" -d '.')"
-    if [ "$a_substring" = "$b_substring" ]
+    a_substring="$(echo "$version_a" | cut -s -f "$dot" -d '.')"
+    b_substring="$(echo "$version_b" | cut -s -f "$dot" -d '.')"
+    if ! [ "$a_substring" = "$b_substring" ]
     then
-      ret=0
-    elif [ "$a_substring" -lt "$b_substring" ]
-    then
-      ret=1
-      break
-    elif [ "$a_substring" -gt "$b_substring" ]
-    then
-      ret=2
-      break
-    else
-      ret=3
-      echo "Error: Version strings are not comparable!"
-      break
+      if [ "$a_substring" -lt "$b_substring" ]
+      then
+        return 1
+      elif [ "$a_substring" -gt "$b_substring" ]
+      then
+        return 2
+      else
+        echo "Error: Version strings are not comparable!"
+        return 3
+      fi
     fi
   done
-  return "$ret"
+  return 0
 }
 
 called="$(basename "$0")"
