Update sfos-upgrade

diff --git a/usr/bin/sfos-upgrade b/usr/bin/sfos-upgrade
--- a/usr/bin/sfos-upgrade
+++ b/usr/bin/sfos-upgrade
@@ -3,7 +3,7 @@ set -o posix
 set -eufC
 
 # Switched to use bash since version 2.1 of this script (in its first two lines), as this ensures that -o pipefail
-# (in line 531) is available, after checking that bash seems to be present in mer-core at least since 2011-10-04 (see
+# (in line 598) is available, after checking that bash seems to be present in mer-core at least since 2011-10-04 (see
 # https://git.merproject.org/mer-core/bash ) and consequently in SailfishOS since its beginnings (checked v1.0.0.5 per
 # curl https://releases.sailfishos.org/sources/sailfish-1.0.0.5-oss.tar.bz2 | tar -tv | fgrep 'bash' , as no earlier
 # released version is available there, e.g. the first ones at https://coderus.openrepos.net/whitesoft/sailversion ).
@@ -35,7 +35,8 @@ askyes ()
   read yn
   if [ -n "$*" ]
   then 
-    echo "Warning due to internal error: The function askyes expects no parameters, but was called with \"${*}\"." >&2 
+    echo "Warning due to internal error: The function askyes expects no parameters, but was called with \"${*}\"." >&2
+    echo "Nevertheless, carrying on." >&2
     retc=2 
   fi
   case "$yn" in
@@ -47,11 +48,6 @@ askyes ()
     exit 4
     ;;
   esac
-
-
-
-
-
   return "$retc"
 }
 
