Update sfos-upgrade

diff --git a/usr/bin/sfos-upgrade b/usr/bin/sfos-upgrade
--- a/usr/bin/sfos-upgrade
+++ b/usr/bin/sfos-upgrade
@@ -3,7 +3,7 @@ set -o posix
 set -eufC
 
 # Switched to use bash since version 2.1 of this script (in its first two lines), as this ensures that -o pipefail
-# (in line 610) is available, after checking that bash seems to be present in mer-core at least since 2011-10-04 (see
+# (in line 611) is available, after checking that bash seems to be present in mer-core at least since 2011-10-04 (see
 # https://git.merproject.org/mer-core/bash ) and consequently in SailfishOS since its beginnings (checked v1.0.0.5 per
 # curl https://releases.sailfishos.org/sources/sailfish-1.0.0.5-oss.tar.bz2 | tar -tv | fgrep 'bash' , as no earlier
 # released version is available there, e.g. the first ones at https://coderus.openrepos.net/whitesoft/sailversion ).
@@ -33,21 +33,22 @@ askyes ()
   # and it exits (instead of returning) when the user asks to abort.
   echo -n " (Y/N) "
   read yn
-  if [ -n "$*" ]
-  then
-    echo "Warning due to internal error: The function askyes expects no parameters, but was called with \"${*}\"." >&2
-    retc=3
-  fi
+  retcode=1
   case "$yn" in
   y|Y)
-    retc=0
+    retcode=0
     ;;
   *)
     echo "Aborting upon user request."
     exit 4
     ;;
   esac
-  return "$retc"
+  if [ -n "$*" ]
+  then
+    echo "Warning due to internal error: The function askyes expects no parameters, but was called with \"${*}\"." >&2
+    retcode=3
+  fi
+  return "$retcode"
 }
 
 compare_versions ()
