Update sfos-upgrade

diff --git a/usr/bin/sfos-upgrade b/usr/bin/sfos-upgrade
--- a/usr/bin/sfos-upgrade
+++ b/usr/bin/sfos-upgrade
@@ -104,7 +104,7 @@ else
   shift
   if [ -n "$*" ]
   then
-    echo "Aborting: No extra parameters expected, but \"$*\" set." 1>&2
+    echo "Aborting: No extra parameters expected, but \"${*}\" set." 1>&2
     exit 3
   fi
   case "$upgrade_release" in
@@ -118,7 +118,7 @@ else
     exit 2
     ;;
   *)
-    echo "Aborting: Inorrect version format \"$upgrade_release\" provided." 1>&2
+    echo "Aborting: Inorrect version format \"${upgrade_release}\" provided." 1>&2
     exit 3
     ;;
   esac
