Update sfos-upgrade

diff --git a/usr/bin/sfos-upgrade b/usr/bin/sfos-upgrade
--- a/usr/bin/sfos-upgrade
+++ b/usr/bin/sfos-upgrade
@@ -181,10 +181,24 @@ then
 fi
 for stop_release in $(echo -e "${recent_stop_releases}\n$known_stop_releases" | grep -v '^$' | sort -u)
 do
-  ( compare_versions "$stop_release" "$installed_release" ) > /dev/null
-  ret="$?"
-  case "$ret" in
-  1|0)
+  field="$(( compare_versions "$stop_release" "$installed_release" ); ret="$?")"
+  case "${ret}-$field" in
+  0-4)
+    field="$(( compare_versions "$stop_release" "$upgrade_release" ); ret="$?")"
+    case "${ret}-$field" in
+    2-4)
+    2-?)
+    if [ "$ret" = "2" ]
+    then
+      echo "Aborting: Trying to DOWNGRADE SailfishOS from $installed_release to ${upgrade_release}, which is \"across\" the stop release ${stop_release}!" >&2
+      echo "Doing that would likely make this SailfishOS installation unusable." >&2
+      echo "The only way to achieve this properly is to execute a \"factory reset\", followed by UPgrading to the intended version." >&2
+      exit 3
+    *)
+      exit "$ret"
+      ;;
+    ;;
+  1-?)
     ( compare_versions "$stop_release" "$upgrade_release" ) > /dev/null
     ret="$?"
     if [ "$ret" = "2" ]
@@ -197,7 +211,7 @@ do
     then exit "$ret"
     fi
     ;;
-  2)
+  2-?)
     ( compare_versions "$stop_release" "$upgrade_release" ) > /dev/null
     ret="$?"
     if [ "$ret" = "1" ]
@@ -218,6 +232,7 @@ do
     fi
     ;;
   *)
+    echo "Comparing versions in \"stop release\" check failed!"
     exit "$ret"
     ;;
   esac
