Update tidy_log-dupes

diff --git a/usr/bin/tidy_log-dupes b/usr/bin/tidy_log-dupes
--- a/usr/bin/tidy_log-dupes
+++ b/usr/bin/tidy_log-dupes
@@ -70,7 +70,7 @@ do
         echo " tidied successfully."
       else
         logs_nodelete="$(expr "$logs_nodelete" '+' "1")"
-        echo " tidied, but failed to remove it."
+        echo " tidied, but failed to remove it!"
       fi
     else
       rm -f "$tidied_log"
@@ -95,15 +95,15 @@ case $retc in
     else retc=120
     fi
     if [ "$logs_count" -eq "$(expr "$logs_succcess" '+' "$logs_remain")" ]
-    then echo "Error: Processed $logs_count untidy log files in ${logdir}, of these $logs_success sucessfully, $logs_nodelete tidied but failed to delete them and failed to tidy $logs_failed log files (hence $logs_remain remain)!" >&2
-    else echo "Error: Processed $logs_count untidy log files in ${logdir}, of these $logs_success sucessfully, $logs_nodelete tidied but failed to delete them and failed to tidy $logs_failed log files (hence $logs_remain remain)!  Additionally these numbers do not add up, indicating an internal logic flaw!" >&2
+    then echo "Error: Processed $logs_count untidy log file(s) in ${logdir}, of these $logs_success sucessfully, $logs_nodelete tidied but failed to delete them and failed to tidy $logs_failed (hence $logs_remain untidy log files remain)!" >&2
+    else echo "Error: Processed $logs_count untidy log file(s) in ${logdir}, of these $logs_success sucessfully, $logs_nodelete tidied but failed to delete them and failed to tidy $logs_failed (hence $logs_remain untidy log files remain)!  Additionally these numbers do not add up, indicating an internal logic flaw!" >&2
     fi
   fi
   ;;
 121)
   case "$logs_count$logs_success$logs_nodelete$logs_failed" in
   0000)
-    echo "Notice: Found no untidy log files in $logdir ." >&2
+    echo "Notice: Found no untidy log file in $logdir ." >&2
     ;;
   *)
     echo "Warning: Internal logic error, as no untidy log file was found in ${logdir}, but processed $logs_count log files, of these $logs_success sucessfully, $logs_nodelete tidied but failed to delete them and failed to tidy $logs_failed log files!" >&2
