Update tidy_log-dupes

diff --git a/usr/bin/tidy_log-dupes b/usr/bin/tidy_log-dupes
--- a/usr/bin/tidy_log-dupes
+++ b/usr/bin/tidy_log-dupes
@@ -57,7 +57,7 @@ do
   if [ "$logfile" != "$targets" ]
   then
     tidied_log="$(echo "$logfile" | rev | cut -f 2- -d '-' | rev).txt"
-    if cat "$logfile" | sed 's/\cM//g' | sed 's/Installing: [0-9][0-9]*%\x1b\[K//g' | sed 's/\x1b\[K/\n/g' | sed 's/^\[[0-9][0-9]* %] //g' | sed 's/: \[[0-9][0-9]* %]$//g' | sed 's/: [0-9][0-9]*%$//g' | uniq > "$tidied_log"
+    if sed 's/\cM//g' "$logfile" | sed 's/Installing: [0-9][0-9]*%\x1b\[K//g' | sed 's/\x1b\[K/\n/g' | sed 's/^\[[0-9][0-9]* %] //g' | sed 's/: \[[0-9][0-9]* %]$//g' | sed 's/: [0-9][0-9]*%$//g' | uniq > "$tidied_log"
     then rm -f "$logfile"
     elif [ "$retc" -lt "120" ]
     then retc="$(expr "$retc" '+' "1")"
@@ -68,10 +68,10 @@ do
 done
 case $retc in
 [1-9]|[1-9][0-9]|1[0-1][0-9])
-  echo "Warning: Failed to tidy $retc of $logs_count log file(s)!" >&2
+  echo "Warning: Failed to tidy $retc of $logs_count log file(s) in $logdir : The(se) untidied file(s) remain!" >&2
   ;;
 120)
-  echo "Warning: Failed to tidy 120 or more of $logs_count log files!" >&2
+  echo "Warning: Failed to tidy 120 or more of $logs_count log files in $logdir : These untidied files remain!" >&2
   ;;
 121)
   echo "Notice: Found no log file to tidy." >&2
