Update tidy_log-dupes

diff --git a/usr/bin/tidy_log-dupes b/usr/bin/tidy_log-dupes
--- a/usr/bin/tidy_log-dupes
+++ b/usr/bin/tidy_log-dupes
@@ -101,14 +101,10 @@ case $retc in
   fi
   ;;
 121)
-  case "$logs_count$logs_success$logs_nodelete$logs_failed" in
-  0000)
-    echo "Notice: Found no untidy log file in $logdir ." >&2
-    ;;
-  *)
-    echo "Warning: Internal logic error, as no untidy log file was found in ${logdir}, although $called processed $logs_count untidy log file(s), of these $logs_success sucessfully, $logs_nodelete tidied but failed to delete them and $logs_failed failed to tidy!" >&2
-    ;;
-  esac
+  if [ "$logs_count$logs_success$logs_nodelete$logs_failed" = "0000" ]
+  then echo "Notice: Found no untidy log file in $logdir ." >&2
+  else echo "Warning: Internal logic error, as no untidy log file was found in ${logdir}, although $called processed $logs_count untidy log file(s), of these $logs_success sucessfully, $logs_nodelete tidied but failed to delete them and $logs_failed failed to tidy!" >&2
+  fi
 *)
   echo "Warning: Internal logic flaw, $called should never get here (return code is ${retc})!" >&2
   ;;
