Update tidy_log-dupes

diff --git a/usr/bin/tidy_log-dupes b/usr/bin/tidy_log-dupes
--- a/usr/bin/tidy_log-dupes
+++ b/usr/bin/tidy_log-dupes
@@ -86,8 +86,8 @@ case $retc in
   if [ "$logs_remain" -eq "0" ]
   then 
     if [ "$logs_count" -eq "$logs_success" ]
-    then echo "Summary: Processed all $logs_count untidy log files in $logdir successfully." >&2
-    else echo "Warning: Sucessfully processed $logs_success of $logs_count untidy log  in $logdir (without a single failure), but the numbers differ (indicating an internal logic flaw)!" >&2
+    then echo "Summary: Processed $logs_count untidy log file(s) in $logdir successfully." >&2
+    else echo "Warning: Sucessfully processed $logs_success of $logs_count untidy log file(s) in $logdir (without a single failure), but the numbers differ (indicating an internal logic flaw)!" >&2
     fi
   else
     if [ "$logs_remain" -lt "120" ]
